#!/usr/bin/env bash
# =============================================================================
# install-model-router-nginx.sh
# Keeps the per-model ports working once the model router owns the backends.
#
# In router mode one llama-server serves embed, ocr, rank and task on a single
# port, but every caller in and around this stack addresses them by their own
# port. Rather than repoint chat-proxy, the GLM-OCR SDK, Honcho, the Flask OCR
# routes and whatever else on the LAN has the old address written down, nginx
# fronts each of those ports onto the router. The router picks the model from
# the request body, so nothing has to be rewritten on the way through.
#
# Run with MODEL_ROUTER_ENABLED=off (or --remove) to take the shims away again.
# =============================================================================
set -euo pipefail

# GENERATE_ONLY writes the config and stops, so the generation can be checked
# without root and without touching a live nginx.
if [[ "${EUID}" -ne 0 && -z "${GENERATE_ONLY:-}" ]]; then
    echo "Run as root: sudo bash scripts/install-model-router-nginx.sh" >&2
    exit 1
fi

STACK_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
if [[ -f "${STACK_DIR}/config/llm-stack.env" ]]; then
    set -a
    # shellcheck disable=SC1091
    source "${STACK_DIR}/config/llm-stack.env"
    set +a
fi

CONF_NAME="${MODEL_ROUTER_CONF_NAME:-llm-model-router}"
CONF_PATH="${CONF_PATH:-/etc/nginx/sites-available/${CONF_NAME}}"
LINK_PATH="${LINK_PATH:-/etc/nginx/sites-enabled/${CONF_NAME}}"

ROUTER_PORT="${MODEL_ROUTER_PORT:-8013}"
LISTEN_ADDR="${MODEL_ROUTER_NGINX_LISTEN_ADDR:-${LISTEN_HOST:-0.0.0.0}}"
[[ "${LISTEN_ADDR}" == "0.0.0.0" ]] && LISTEN_ADDR=""

remove_conf() {
    rm -f "${LINK_PATH}" "${CONF_PATH}"
    if nginx -t 2>/dev/null; then
        systemctl reload nginx
        echo "Removed nginx model router shims."
    else
        echo "Removed ${CONF_NAME}, but nginx -t failed on the remaining config." >&2
        exit 1
    fi
}

if [[ "${1:-}" == "--remove" || "${MODEL_ROUTER_ENABLED:-off}" != "on" ]]; then
    remove_conf
    exit 0
fi

# Each pooled model's public port. A member whose port is unset is skipped
# rather than defaulted, so turning a member off leaves its port alone.
declare -A MEMBER_PORTS=(
    [EMBED]="${EMBED_PORT:-}"
    [EMBED2]="${EMBED2_PORT:-}"
    [RERANK]="${RERANK_PORT:-}"
    [TASK]="${TASK_PORT:-}"
    [OCR]="${OCR_PORT:-}"
)

MEMBERS="${MODEL_ROUTER_MEMBERS:-EMBED,OCR,RERANK,TASK}"

listen_line() {
    local port="$1"
    if [[ -n "${LISTEN_ADDR}" ]]; then
        printf '    listen %s:%s;\n' "${LISTEN_ADDR}" "${port}"
    else
        printf '    listen %s;\n' "${port}"
        printf '    listen [::]:%s;\n' "${port}"
    fi
}

server_block() {
    local member="$1" port="$2"
    cat <<NGINX
# ${member} -> model router
server {
$(listen_line "${port}")
    server_name _;

    # A request can wait out a cold model load before any tokens are produced,
    # so the read timeout has to be generous. Buffering off because the chat
    # and OCR paths stream.
    proxy_read_timeout 3600s;
    proxy_send_timeout 3600s;
    proxy_buffering off;
    proxy_request_buffering off;
    client_max_body_size 0;

    location / {
        proxy_pass http://127.0.0.1:${ROUTER_PORT};
        proxy_http_version 1.1;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_set_header Connection "";
    }
}
NGINX
}

{
    echo "# Generated by scripts/install-model-router-nginx.sh — do not edit."
    echo "# Fronts the per-model ports onto the router on 127.0.0.1:${ROUTER_PORT}."
    echo
} > "${CONF_PATH}"

INSTALLED=()
IFS=',' read -ra WANTED <<< "${MEMBERS}"
for member in "${WANTED[@]}"; do
    member="$(tr -d '[:space:]' <<< "${member}" | tr '[:lower:]' '[:upper:]')"
    [[ -z "${member}" ]] && continue
    port="${MEMBER_PORTS[${member}]:-}"
    if [[ -z "${port}" ]]; then
        echo "  skipping ${member}: no public port configured" >&2
        continue
    fi
    if [[ "${port}" == "${ROUTER_PORT}" ]]; then
        echo "  skipping ${member}: its port is the router's own port" >&2
        continue
    fi
    server_block "${member}" "${port}" >> "${CONF_PATH}"
    echo >> "${CONF_PATH}"
    INSTALLED+=("${member}:${port}")
done

if [[ ${#INSTALLED[@]} -eq 0 ]]; then
    echo "No pooled members had a public port; nothing to install." >&2
    remove_conf
    exit 1
fi

if [[ -n "${GENERATE_ONLY:-}" ]]; then
    echo "Wrote ${CONF_PATH} (generate-only; nginx untouched)"
    exit 0
fi

ln -sfn "${CONF_PATH}" "${LINK_PATH}"

if ! nginx -t; then
    echo "nginx rejected the generated config; rolling back." >&2
    rm -f "${LINK_PATH}" "${CONF_PATH}"
    nginx -t >/dev/null 2>&1 && systemctl reload nginx
    exit 1
fi
systemctl reload nginx

echo "Installed nginx model router shims -> 127.0.0.1:${ROUTER_PORT}"
for entry in "${INSTALLED[@]}"; do
    echo "  ${entry%%:*} on port ${entry##*:}"
done
